package net.orca.ocean.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class BigKelpFishAnimationDefinitions {
        public static final AnimationDefinition swim = AnimationDefinition.Builder.withLength(1.48f).looping()
                .addAnimation("body",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("body",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 12f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.04f, KeyframeAnimations.degreeVec(0f, 11.33f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(0f, 9.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 6.43f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 2.74f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, -1.25f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24000000000000002f, KeyframeAnimations.degreeVec(0f, -5.11f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, -8.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, -10.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, -11.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.39999999999999997f, KeyframeAnimations.degreeVec(0f, -11.74f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.43999999999999995f, KeyframeAnimations.degreeVec(0f, -10.26f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4799999999999999f, KeyframeAnimations.degreeVec(0f, -7.65f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5199999999999999f, KeyframeAnimations.degreeVec(0f, -4.18f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5599999999999999f, KeyframeAnimations.degreeVec(0f, -0.25f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 3.71f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 7.26f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 10f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7200000000000001f, KeyframeAnimations.degreeVec(0f, 11.62f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7600000000000001f, KeyframeAnimations.degreeVec(0f, 11.96f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8000000000000002f, KeyframeAnimations.degreeVec(0f, 10.96f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8400000000000002f, KeyframeAnimations.degreeVec(0f, 8.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8800000000000002f, KeyframeAnimations.degreeVec(0f, 5.56f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9200000000000003f, KeyframeAnimations.degreeVec(0f, 1.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000003f, KeyframeAnimations.degreeVec(0f, -2.25f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0000000000000002f, KeyframeAnimations.degreeVec(0f, -6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0400000000000003f, KeyframeAnimations.degreeVec(0f, -9.08f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0800000000000003f, KeyframeAnimations.degreeVec(0f, -11.16f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1200000000000003f, KeyframeAnimations.degreeVec(0f, -11.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1600000000000004f, KeyframeAnimations.degreeVec(0f, -11.49f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2000000000000004f, KeyframeAnimations.degreeVec(0f, -9.71f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2400000000000004f, KeyframeAnimations.degreeVec(0f, -6.85f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2800000000000005f, KeyframeAnimations.degreeVec(0f, -3.23f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3200000000000005f, KeyframeAnimations.degreeVec(0f, 0.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3600000000000005f, KeyframeAnimations.degreeVec(0f, 4.65f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4000000000000006f, KeyframeAnimations.degreeVec(0f, 8.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4400000000000006f, KeyframeAnimations.degreeVec(0f, 10.52f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.48f, KeyframeAnimations.degreeVec(0f, 11.83f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -21.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.04f, KeyframeAnimations.degreeVec(0f, -14.84f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(0f, -6.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 1.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 10.08f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 17.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24000000000000002f, KeyframeAnimations.degreeVec(0f, 22.78f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 25.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 25.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 22.78f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.39999999999999997f, KeyframeAnimations.degreeVec(0f, 17.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.43999999999999995f, KeyframeAnimations.degreeVec(0f, 10.08f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4799999999999999f, KeyframeAnimations.degreeVec(0f, 1.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5199999999999999f, KeyframeAnimations.degreeVec(0f, -6.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5599999999999999f, KeyframeAnimations.degreeVec(0f, -14.84f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, -21.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -24.89f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, -25.98f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7200000000000001f, KeyframeAnimations.degreeVec(0f, -24.17f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7600000000000001f, KeyframeAnimations.degreeVec(0f, -19.68f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8000000000000002f, KeyframeAnimations.degreeVec(0f, -13f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8400000000000002f, KeyframeAnimations.degreeVec(0f, -4.87f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8800000000000002f, KeyframeAnimations.degreeVec(0f, 3.8f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9200000000000003f, KeyframeAnimations.degreeVec(0f, 12.05f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000003f, KeyframeAnimations.degreeVec(0f, 18.95f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0000000000000002f, KeyframeAnimations.degreeVec(0f, 23.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0400000000000003f, KeyframeAnimations.degreeVec(0f, 25.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0800000000000003f, KeyframeAnimations.degreeVec(0f, 25.18f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1200000000000003f, KeyframeAnimations.degreeVec(0f, 21.66f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1600000000000004f, KeyframeAnimations.degreeVec(0f, 15.72f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2000000000000004f, KeyframeAnimations.degreeVec(0f, 8.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2400000000000004f, KeyframeAnimations.degreeVec(0f, -0.54f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2800000000000005f, KeyframeAnimations.degreeVec(0f, -9.06f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3200000000000005f, KeyframeAnimations.degreeVec(0f, -16.57f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3600000000000005f, KeyframeAnimations.degreeVec(0f, -22.24f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4000000000000006f, KeyframeAnimations.degreeVec(0f, -25.43f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4400000000000006f, KeyframeAnimations.degreeVec(0f, -25.79f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.48f, KeyframeAnimations.degreeVec(0f, -23.29f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail2",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -13f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.04f, KeyframeAnimations.degreeVec(0f, -19.68f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(0f, -24.17f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, -25.98f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, -24.89f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, -21.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24000000000000002f, KeyframeAnimations.degreeVec(0f, -14.84f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, -6.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 1.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 10.08f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.39999999999999997f, KeyframeAnimations.degreeVec(0f, 17.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.43999999999999995f, KeyframeAnimations.degreeVec(0f, 22.78f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4799999999999999f, KeyframeAnimations.degreeVec(0f, 25.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5199999999999999f, KeyframeAnimations.degreeVec(0f, 25.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.5599999999999999f, KeyframeAnimations.degreeVec(0f, 22.78f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 17.4f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 10.08f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 1.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7200000000000001f, KeyframeAnimations.degreeVec(0f, -6.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.7600000000000001f, KeyframeAnimations.degreeVec(0f, -14.84f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8000000000000002f, KeyframeAnimations.degreeVec(0f, -21.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8400000000000002f, KeyframeAnimations.degreeVec(0f, -24.89f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8800000000000002f, KeyframeAnimations.degreeVec(0f, -25.98f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9200000000000003f, KeyframeAnimations.degreeVec(0f, -24.17f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000003f, KeyframeAnimations.degreeVec(0f, -19.68f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0000000000000002f, KeyframeAnimations.degreeVec(0f, -13f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0400000000000003f, KeyframeAnimations.degreeVec(0f, -4.87f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.0800000000000003f, KeyframeAnimations.degreeVec(0f, 3.8f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1200000000000003f, KeyframeAnimations.degreeVec(0f, 12.05f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.1600000000000004f, KeyframeAnimations.degreeVec(0f, 18.95f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2000000000000004f, KeyframeAnimations.degreeVec(0f, 23.75f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2400000000000004f, KeyframeAnimations.degreeVec(0f, 25.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2800000000000005f, KeyframeAnimations.degreeVec(0f, 25.18f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3200000000000005f, KeyframeAnimations.degreeVec(0f, 21.66f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.3600000000000005f, KeyframeAnimations.degreeVec(0f, 15.72f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4000000000000006f, KeyframeAnimations.degreeVec(0f, 8.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.4400000000000006f, KeyframeAnimations.degreeVec(0f, -0.54f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.48f, KeyframeAnimations.degreeVec(0f, -9.06f, 0f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
        public static final AnimationDefinition swimIdle = AnimationDefinition.Builder.withLength(3f).looping()
                .addAnimation("body",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("body",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0.78f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0.23f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, -0.43f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -0.9f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -0.98f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(0f, -0.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -0.02f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0.6f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, 0.97f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(0f, 0.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(0f, 0.46f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(0f, -0.19f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(0f, -0.76f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(0f, -1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, -0.81f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, -0.27f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(0f, 0.39f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(0f, 0.88f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.96f, KeyframeAnimations.degreeVec(0f, 0.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 2.01f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 2.96f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 2.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 1.16f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -0.81f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -2.43f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(0f, -3f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -2.27f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -0.56f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, 1.39f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(0f, 2.74f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(0f, 2.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(0f, 1.81f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(0f, -0.06f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(0f, -1.91f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, -2.93f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, -2.69f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(0f, -1.28f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(0f, 0.69f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.96f, KeyframeAnimations.degreeVec(0f, 1.61f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail2",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -0.31f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 1.61f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 2.83f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 2.83f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 1.61f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -0.31f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(0f, -2.1f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -2.98f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -2.57f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, -1.05f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(0f, 0.93f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(0f, 2.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(0f, 2.99f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(0f, 2.19f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(0f, 0.44f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, -1.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, -2.79f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(0f, -2.87f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(0f, -1.71f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.96f, KeyframeAnimations.degreeVec(0f, -0.81f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("leftFin",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 45f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("rightFin",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("leftPelvic",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 45f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("rightPelvic",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
}
