package net.orca.ocean.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class OrcaAnimationDefinitions {
        public static final AnimationDefinition swim = AnimationDefinition.Builder.withLength(2f).looping()
                .addAnimation("head",
                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                new Keyframe(0f, KeyframeAnimations.posVec(0f, 4.12f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.posVec(0f, 3.84f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 3.64f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 3.53f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.posVec(0f, 3.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 3.57f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 3.73f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 3.97f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 4.28f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 4.63f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 5.37f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 5.72f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.posVec(0f, 6.03f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.posVec(0f, 6.27f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 6.43f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 6.5f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.posVec(0f, 6.47f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.posVec(0f, 6.36f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.posVec(0f, 6.16f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.posVec(0f, 5.88f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.posVec(0f, 5.55f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 5.19f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.posVec(0f, 4.81f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.posVec(0f, 4.45f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.posVec(0f, 4.12f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("head",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(3.24f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(2.55f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(1.7f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(-0.25f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.degreeVec(-1.24f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-2.14f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.degreeVec(-2.92f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(-3.51f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.degreeVec(-3.87f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-4f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.degreeVec(-3.87f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.degreeVec(-3.51f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.degreeVec(-2.92f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-2.14f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.degreeVec(-1.24f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(-0.25f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.degreeVec(0.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(1.7f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.degreeVec(2.55f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.degreeVec(3.24f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.degreeVec(3.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.degreeVec(3.97f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.degreeVec(3.97f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.degreeVec(3.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(3.24f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(18.6f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(19.84f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.degreeVec(19.84f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(18.6f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.degreeVec(16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(12.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.degreeVec(8.52f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.degreeVec(-1.26f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-6.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.degreeVec(-10.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.degreeVec(-14.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.degreeVec(-17.53f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-19.37f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(-19.37f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.degreeVec(-17.53f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(-14.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.degreeVec(-10.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-6.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.degreeVec(-1.26f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.degreeVec(3.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.degreeVec(8.52f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.degreeVec(12.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("fluke",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(-16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(-12.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(-8.52f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(1.26f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.degreeVec(6.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(10.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.degreeVec(14.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(17.53f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.degreeVec(19.37f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.degreeVec(19.37f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.degreeVec(17.53f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.degreeVec(14.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(10.72f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.degreeVec(6.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(1.26f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.degreeVec(-3.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(-8.52f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.degreeVec(-12.75f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.degreeVec(-16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.degreeVec(-18.6f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.degreeVec(-19.84f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.degreeVec(-19.84f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.degreeVec(-18.6f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(-16.18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("flipperLeft",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.72f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.97f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.97f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.72f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, -12.5f, -2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, -12.5f, -1.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -12.5f, -0.75f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, -12.5f, 0.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, -12.5f, 1.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.degreeVec(0f, -12.5f, 2.14f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.degreeVec(0f, -12.5f, 2.92f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.degreeVec(0f, -12.5f, 3.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -12.5f, 3.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, -12.5f, 4f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, -12.5f, 3.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.degreeVec(0f, -12.5f, 3.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, -12.5f, 2.92f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.degreeVec(0f, -12.5f, 2.14f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.degreeVec(0f, -12.5f, 1.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.degreeVec(0f, -12.5f, 0.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, -12.5f, -0.75f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.degreeVec(0f, -12.5f, -1.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, -12.5f, -2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, -12.5f, -3.24f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("flipperRight",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.08f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.72f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.97f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.97f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.72f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 12.5f, 2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 12.5f, 1.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 12.5f, 0.75f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 12.5f, -0.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 12.5f, -1.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.88f, KeyframeAnimations.degreeVec(0f, 12.5f, -2.14f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.96f, KeyframeAnimations.degreeVec(0f, 12.5f, -2.92f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.04f, KeyframeAnimations.degreeVec(0f, 12.5f, -3.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 12.5f, -3.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 12.5f, -4f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 12.5f, -3.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.36f, KeyframeAnimations.degreeVec(0f, 12.5f, -3.51f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, 12.5f, -2.92f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.52f, KeyframeAnimations.degreeVec(0f, 12.5f, -2.14f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.6f, KeyframeAnimations.degreeVec(0f, 12.5f, -1.24f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.68f, KeyframeAnimations.degreeVec(0f, 12.5f, -0.25f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 12.5f, 0.75f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.84f, KeyframeAnimations.degreeVec(0f, 12.5f, 1.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 12.5f, 2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 12.5f, 3.24f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
        public static final AnimationDefinition swimIdle = AnimationDefinition.Builder.withLength(3f).looping()
                .addAnimation("head",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(-4.09f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(-4.27f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(-4.54f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-4.85f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(-5.19f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-5.5f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(-5.76f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-5.93f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(-6f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(-5.96f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(-5.81f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(-5.57f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(-5.27f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(-4.94f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(-4.61f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(-4.33f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(-4.12f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(-4.01f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(-4.01f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3f, KeyframeAnimations.degreeVec(-4.09f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("tail",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(-21.35f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(-21.01f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(-21.13f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-21.67f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(-22.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-23.76f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(-25.08f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-26.39f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(-27.55f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(-28.42f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(-28.91f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(-28.97f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(-28.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(-27.8f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(-26.7f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(-25.42f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(-24.09f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(-22.86f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(-21.87f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3f, KeyframeAnimations.degreeVec(-21.35f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("fluke",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(-10.99f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(-9.74f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(-9.08f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-9.08f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(-9.74f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-10.99f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(-12.67f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-14.62f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(-16.61f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(-18.42f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(-19.85f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(-20.74f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(-20.99f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(-20.58f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(-19.54f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(-18f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(-16.12f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(-14.12f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(-12.22f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3f, KeyframeAnimations.degreeVec(-10.99f, 0f, 0f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("flipperLeft",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5.48f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 5.98f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 5.81f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 3.63f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 0f, 1.85f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(0f, 0f, -0.13f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, -2.09f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, -3.82f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, 0f, -5.13f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(0f, 0f, -5.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(0f, 0f, -5.95f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(0f, 0f, -5.37f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(0f, 0f, -4.2f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(0f, 0f, -2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, 0f, -0.63f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 1.37f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(0f, 0f, 3.21f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(0f, 0f, 4.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 5.48f),
                                        AnimationChannel.Interpolations.LINEAR)))
                .addAnimation("flipperRight",
                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -5.48f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, -5.98f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, -5.81f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -3.63f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 0f, -1.85f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(0.9600000000000001f, KeyframeAnimations.degreeVec(0f, 0f, 0.13f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 2.09f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 3.82f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.44f, KeyframeAnimations.degreeVec(0f, 0f, 5.13f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(0f, 0f, 5.87f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.7599999999999998f, KeyframeAnimations.degreeVec(0f, 0f, 5.95f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(1.9199999999999997f, KeyframeAnimations.degreeVec(0f, 0f, 5.37f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.0799999999999996f, KeyframeAnimations.degreeVec(0f, 0f, 4.2f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.2399999999999998f, KeyframeAnimations.degreeVec(0f, 0f, 2.55f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, 0f, 0.63f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, -1.37f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.72f, KeyframeAnimations.degreeVec(0f, 0f, -3.21f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(2.8800000000000003f, KeyframeAnimations.degreeVec(0f, 0f, -4.7f),
                                        AnimationChannel.Interpolations.LINEAR),
                                new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, -5.48f),
                                        AnimationChannel.Interpolations.LINEAR))).build();
}
